---
- include_vars: "{{ ansible_os_family }}.yml"

- include: ssh.yml
  when: nova.enable_ssh|bool
  tags:
    - ssh

- include: libvirt.yml
  when: nova.compute_driver == "nova.virt.libvirt.LibvirtDriver" or nova.compute_driver == "libvirt.LibvirtDriver"
  tags:
    - libvirt
    - libvirtd

- include: docker.yml
  when: nova.compute_driver == "novadocker.virt.docker.DockerDriver"

- name: install nova data plan requirements
  action: "{{ ansible_pkg_mgr }} name=sysfsutils"

- name: nova instances directory
  file:
    dest: "{{ nova.state_path }}/instances"
    state: directory
    owner: nova

- name: nbd module
  lineinfile: dest="{{ nbd_load_module_dest }}" line="nbd" create=yes

- name: probe nbd
  modprobe: name=nbd state=present

- name: check if SMT is enabled
  command: "ppc64_cpu --smt"
  failed_when: False
  changed_when: False
  register: smt
  when: ansible_architecture == "ppc64le"

- name: disable SMT for ppc64le
  command: "ppc64_cpu --smt=off"
  when: ansible_architecture == "ppc64le" and not smt.stdout|search("SMT is off")

- name: enable cinder encryption
  template: src=etc/nova/nova.cinder_encryption.conf dest=/etc/nova/nova.cinder_encryption.conf mode=0640
            owner=root group=nova
  notify: restart nova services
  when: cinder.fixed_key is defined

- name: disable  cinder encryption
  file: dest=/etc/nova/nova.cinder_encryption.conf state=absent
  notify: restart nova services
  when: cinder.fixed_key is not defined

- name: install nova-compute service
  upstart_service: name=nova-compute user=nova cmd=/usr/local/bin/nova-compute
                   config_dirs=/etc/nova
  when: ansible_os_family != "Ibm_powerkvm"

- name: install nova-compute service for ubuntu 15.x,16.x and Ibm_powerkvm, Copy nova-compute.service
  template: src=lib/systemd/system/nova-compute.service dest=/lib/systemd/system/nova-compute.service mode=0644
  when: ansible_distribution_version == "15.04" or ansible_distribution_version == "15.10" or ansible_distribution_version == "16.04" or ansible_os_family == "Ibm_powerkvm"

- name: install nova-compute service for ubuntu 15.x and 16.x and Ibm_powerkvm, Reload systemctl
  command: systemctl daemon-reload
  when: ansible_distribution_version == "15.04" or ansible_distribution_version == "15.10" or ansible_distribution_version == "16.04" or ansible_os_family == "Ibm_powerkvm"

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify: restart nova services
  when: (git_result.changed) and
        upgrade | default('False') | bool

- meta: flush_handlers

- name: start nova-compute
  service: name=nova-compute state=started

