---
- name: gather nova pubkeys
  user:
    name: nova
    generate_ssh_key: yes
  register: nova_user

- name: nova authorized_keys
  template:
    src: var/lib/nova/ssh/authorized_keys
    dest: "{{ nova.state_path }}/.ssh/authorized_keys"
    owner: nova
    group: nova
    mode: 0600

- name: nova known_hosts
  template:
    src: var/lib/nova/ssh/known_hosts
    dest: "{{ nova.state_path }}/.ssh/known_hosts"
    owner: nova
    group: nova
    mode: 0600

- name: root ssh dir
  file:
    path: /root/.ssh
    mode: 0700
    state: directory

- name: nova known_hosts root symlink (for libvirt)
  file:
    src: "{{ nova.state_path }}/.ssh/known_hosts"
    path: /root/.ssh/known_hosts
    state: link

- name: nova bin directory
  file:
    dest: "{{ nova.state_path }}/bin"
    state: directory
    owner: nova
    group: nova
    mode: 0755

- name: nova verify-ssh
  template:
    src: var/lib/nova/bin/verify-ssh
    dest: "{{ nova.state_path }}/bin/verify-ssh"
    owner: nova
    group: nova
    mode: 0755

- name: verify ssh among compute nodes
  command: sudo -u nova -H /bin/sh -c {{ nova.state_path }}/bin/verify-ssh
