---
endpoints:
  main: "{{ fqdn }}"
  db: "{{ undercloud_floating_ip }}"
  rabbit: "{{ undercloud_floating_ip }}"
  memcache: "{{ undercloud_floating_ip }}:11211"
  identity_uri: https://{{ fqdn }}:35357
  auth_uri: https://{{ fqdn }}:5000
  nova:
    name: nova
    type: compute
    description: Compute Service
    version: v2
    url:
      admin: https://{{ fqdn }}:8774
      internal: https://{{ fqdn }}:8774
      public: https://{{ fqdn }}:8774
      path: v2/%(tenant_id)s
    port:
      backend_api: 8774
  glance:
    name: glance
    type: image
    description: Image Service
    url:
      admin: https://{{ fqdn }}:9292
      internal: https://{{ fqdn }}:9292
      public: https://{{ fqdn }}:9292
    port:
      backend_api: 9292
  cinder:
    name: cinder
    type: volume
    description: Volume Service
    version: v1
    url:
      admin: https://{{ fqdn }}:8776
      internal: https://{{ fqdn }}:8776
      public: https://{{ fqdn }}:8776
      path: v1/%(tenant_id)s
    port:
      backend_api: 8776
  cinderv2:
    name: cinderv2
    type: volume
    description: 'Volume Service v2'
    version: v2
    url:
      admin: https://{{ fqdn }}:8776
      internal: https://{{ fqdn }}:8776
      public: https://{{ fqdn }}:8776
      path: v2/%(tenant_id)s
  keystone:
    name: keystone
    type: identity
    description: 'Identity Service'
    version: v2.0
    url:
      internal: https://{{ fqdn }}:5000
      public: https://{{ fqdn }}:5000
      admin: https://{{ fqdn }}:35357
    port:
      backend_api: 5000
  keystone_admin:
    port:
      backend_api: 35357
  keystone_legacy:
    port:
      backend_api: 5001
  keystonev3:
    name: keystonev3
    type: identity
    description: 'Identity Service v3'
    version: v3
    url:
      internal: https://{{ fqdn }}:5000
      public: https://{{ fqdn }}:5000
      admin: https://{{ fqdn }}:35357
    port:
      backend_api: 5000
 novnc:
    url:
      admin: https://{{ fqdn }}:6080
      internal: https://{{ fqdn }}:6080
      public: https://{{ fqdn }}:6080
    port:
      backend_api: 6081
      haproxy_api: 6080
  neutron:
    name: neutron
    type: network
    description: 'Network Service'
    url:
      admin: https://{{ fqdn }}:9696
      internal: https://{{ fqdn }}:9696
      public: https://{{ fqdn }}:9696
    port:
      backend_api: 9696
