---
repos: []
apt_repos:
  docker:
    repo: 'https://get.docker.com/ubuntu'
    key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD8576A8BA88D21E9'
  haproxy:
    repo: 'http://ppa.launchpad.net/vbernat/haproxy-1.5/ubuntu'
    key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCFFB779AADC995E4F350A060505D97A41C61B9CD'
  percona:
    repo: 'http://repo.percona.com/apt'
    key_url: 'https://www.percona.com/redir/downloads/RPM-GPG-KEY-percona'
  rabbitmq:
    repo: 'http://www.rabbitmq.com/debian/'
    key_url: 'https://www.rabbitmq.com/rabbitmq-signing-key-public.asc'
  cloud_archive:
    repo: 'http://ubuntu-cloud.archive.canonical.com/ubuntu'
  erlang:
    repo: 'http://packages.erlang-solutions.com/debian'
    key_url: 'https://packages.erlang-solutions.com/debian/erlang_solutions.asc'
  ceph:
    repo: 'http://ceph.com/debian-'
    key_url: 'https://download.ceph.com/keys/release.asc'
  mongodb:
    repo: 'http://repo.mongodb.org/apt/ubuntu'
    key_url: 'https://docs.mongodb.org/10gen-gpg-key.asc'
