---
- name: update timezone
  shell: "timedatectl set-timezone `cat /etc/timezone`"  #"{{ timezone_update }}"

- name: refresh CAs
  command: "{{ update_ca_certs }}" 

- name: apply-sysctl
  shell: "cat /etc/sysctl.conf /etc/sysctl.d/*.conf | sysctl -e -p -"

- name: update grub config
  command: "{{ update_grub }}"

- include: ssh.yml

- name: restart-ntp
  service: name={{ ntp_service }} state=restarted

- name: load sensors
  shell: /usr/sbin/sensors-detect < /dev/null

- name: update package index apt
  apt: update_cache=yes cache_valid_time=3600

- name: update package index yum
  yum: name=* update_cache=yes state=latest

