---
- include_vars: "{{ ansible_os_family }}.yml"

- name: install required packages and diagnostic tools
  action: "{{ ansible_pkg_mgr }} name={{ item }}"
  with_items:
    - "{{ diagnostic_tools }}"

- name: update iproute to latest ppa
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - "{{ iproute_pkg }}"


- name: ml2 dataplane config
  template: src=etc/neutron/plugins/ml2/ml2_plugin_dataplane.ini
            dest=/etc/neutron/plugins/ml2/ml2_plugin_dataplane.ini
            mode=0644
  when: neutron.plugin == 'ml2'


- name: install neutron-linuxbridge-agent service
  upstart_service: name=neutron-linuxbridge-agent
                   user=neutron
                   cmd=/usr/local/bin/neutron-linuxbridge-agent
                   config_dirs=/etc/neutron
                   config_files=/etc/neutron/neutron.conf,/etc/neutron/plugins/ml2/ml2_plugin.ini,/etc/neutron/plugins/ml2/ml2_plugin_dataplane.ini
  when: neutron.plugin == 'ml2' and neutron.mech_driver == 'linuxbridge' and ansible_os_family == "Debian"

- name: install neutron-openvswitch-agent service
  upstart_service: name=neutron-openvswitch-agent
                   user=neutron
                   cmd=/usr/local/bin/neutron-openvswitch-agent
                   config_dirs=/etc/neutron
                   config_files=/etc/neutron/neutron.conf,/etc/neutron/plugins/ml2/ml2_plugin.ini,/etc/neutron/plugins/ml2/ml2_plugin_dataplane.ini,/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
                   prestart_script=/usr/local/bin/neutron-ovs-cleanup
  when: neutron.plugin == 'ml2' and neutron.mech_driver == 'ovs' and ansible_os_family == "Debian"

- name: install neutron-linuxbridge-agent service, Copy neutron-linuxbridge-agent.service
  template: src=lib/systemd/system/neutron-linuxbridge-agent.service dest=/lib/systemd/system/neutron-linuxbridge-agent.service mode=0644
  when: ( ansible_distribution_version == "15.04" or ansible_distribution_version == "15.10" or ansible_distribution_version == "16.04" or ansible_os_family == 'Ibm_powerkvm' ) and neutron.mech_driver == 'linuxbridge'

- name: install neutron-openvswitch-agent.service, Copy neutron-openvswitch-agent.service
  template: src=lib/systemd/system/neutron-openvswitch-agent.service dest=/lib/systemd/system/neutron-openvswitch-agent.service mode=0644
  when: ( ansible_distribution_version == "15.04" or ansible_distribution_version == "15.10" or ansible_distribution_version == "16.04" or ansible_os_family == 'Ibm_powerkvm' ) and neutron.mech_driver == 'ovs'

- name: Reload systemctl
  command: systemctl daemon-reload
  when: ansible_distribution_version == "15.04" or ansible_distribution_version == "15.10" or ansible_distribution_version == "16.04"  or ansible_os_family == 'Ibm_powerkvm'

- name: trigger openvswitch service restart
  debug:
    msg: "Triggering openvswitch service restart"
  notify: restart neutron openvswitch service
  when: neutron.mech_driver == 'ovs'
  
- name: trigger linuxbridge service restart
  debug:
    msg: "Triggering linuxbridge service restart"
  notify: restart neutron linuxbridge service
  when: neutron.mech_driver == 'linuxbridge'

- meta: flush_handlers

- name: start neutron-linuxbridge-agent
  service: name=neutron-linuxbridge-agent state=started
  when: neutron.plugin == 'ml2' and neutron.mech_driver == 'linuxbridge'

- name: start neutron-openvswitch-agent
  service: name=neutron-openvswitch-agent state=started
  when: neutron.plugin == 'ml2' and neutron.mech_driver == 'ovs'

- name: cleanup interface logs
  template: src=etc/cron.daily/cleanup-neutron-interfaces
            dest=/etc/cron.daily/cleanup-neutron-interfaces
            mode=0755 owner=root

