---
- name: ifup br-ex
  command: ifup br-ex
  failed_when: False

- name: restart neutron lbaas agent
  service: name=neutron-lbaasv2-agent state=restarted_if_running
  when: restart|default('True') and ((neutron.lbaas.enable == "smart" and
                     groups['controller'][0] not in groups['compute']) or
                     neutron.lbaas.enable|bool)

- name: restart xorp
  service: name=xorp state=restarted sleep=10
  ignore_errors: True
