---
# FIXME(cmt): for whatever reason the PPA doesnt like the signature on openvswitch-datapath-dkms
# Linux 3.13 and later include the OVS datapath
- name: force install of ovs dkms
  apt: pkg=openvswitch-datapath-dkms force=yes
  when: ansible_distribution_version == "12.04"

- name: install other ovs packages
  apt: pkg={{ item }}
  with_items:
    - openvswitch-switch
    - vlan
    - bridge-utils

- name: ovs int bridge
  ovs_bridge: name=br-int state=present

