---
- include_vars: "{{ ansible_os_family }}.yml"

- name: set hostname
  hostname: name={{ hostname }}
  when: hostname is defined

- meta: flush_handlers

- name: update package index apt
  apt: update_cache=yes cache_valid_time=3600
  tags: ['prereboot']
  when: ansible_pkg_mgr == "apt"

- name: update package index yum
  yum: name=* update_cache=yes state=latest
  tags: ['prereboot']
  when: ansible_pkg_mgr == "yum"
  
- include: system-tools.yml

- name: python dependencies
  action: "{{ ansible_pkg_mgr }} name={{ item }} "
  with_items:
    - "{{ python_dependencies_list }}" 

- include: python.yml
  tags: pip, python

- include: ruby.yml
  tags: ruby

- name: set UTC timezone
  template: src=etc/timezone dest=/etc/timezone owner=root group=root mode=0644
  notify:
    - update timezone

- name: state path base directory
  file: dest={{ state_path_base }} state=directory

- include: ssl.yml
  tags: ssl

- include: ssh.yml

- include: networking.yml

- include: system-file-permissions.yml

- include: ntp.yml
  tags: ntp

- include: disable-swap.yml

- name: remove unwanted packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=absent"
  with_items: "{{ common.packages_to_remove }}"

- name: include stack name in /etc/issue
  lineinfile: dest=/etc/issue regexp="^{{ stack_env }} OpenStack Node" line="{{ stack_env }} OpenStack Node"
