---
- name: openstack creds
  template: src=root/stackrc dest=/root/stackrc
  when: client.write_stackrc|bool

- name: install required packages for clients
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ client.apt_packages }}"

- name: install openstack clients
  pip: name={{ item }}
  with_items: "{{ client.names }}"
  notify:
    - update ca certs

- name: fix ssl certs for requests for keystone-client on trusty
  file: src=/etc/ssl/certs/ca-certificates.crt
        dest=/usr/local/lib/python2.7/dist-packages/requests/cacert.pem
        owner=root
        mode=0644 state=link force=yes

- name: migrate neutron services script
  template: src=usr/local/bin/migrate_neutron_services
            dest=/usr/local/bin/migrate_neutron_services mode=0755
