---
# NOTE: Glance does not know how to proxy copy-from URLs, so we should instead
# download the image files locally and create images using the file method.
- name: create image directory
  file: path=/opt/stack/glance-images state=directory mode=0755

- name: discover existing images
  stat:
    path: /opt/stack/glance-images/{{ item.filename }}
  run_once: True
  register: images_downloaded
  with_items: "{{ glance.images }}"

- name: download any necessary images
  get_url:
    url: "{{ item.0.url }}"
    dest: "/opt/stack/glance-images/{{ item.0.filename }}"
  run_once: True
  when: item.1
  with_together:
    - "{{ glance.images }}"
    - "{{ images_downloaded.results }}"

- name: default images
  glance_image: name={{ item.name }}
                file="/opt/stack/glance-images/{{ item.filename }}"
                container_format=bare
                disk_format=qcow2
                auth_url={{ endpoints.auth_uri }}
                login_tenant_name=admin
                login_username=admin
                login_password={{ secrets.admin_password }}
                is_public=yes
                timeout=12000
  with_items: "{{ glance.images }}"
  run_once: true
